volumes:
  pg_data:
  static:
  media:
  backend_static:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    image: backend
    build:
      context: ./backend/
    env_file: .env
    volumes:
      - static:/static
      - backend_static:/backend_static  # Обновленный путь для статических файлов
      - media:/app/media
    command: >
      sh -c "python manage.py makemigrations
      && python manage.py makemigrations recipes
      && python manage.py migrate
      && python manage.py migrate recipes
      && python manage.py collectstatic --noinput
      && python manage.py load_ingridients data/ingredients.json
      && python manage.py load_tags data/tags.json
      && gunicorn --bind 0.0.0.0:8080 backend.wsgi"
    depends_on:
      - db

  frontend:
    image: frontend
    build:
      context: ./frontend/
    env_file: .env
    # Файлы копируются в Dockerfile
    volumes:
      - static:/static

  nginx:
    image: nginx
    build:
      context: ./nginx/
    env_file: .env
    volumes:
      - static:/static
      - backend_static:/backend_static  # Добавляем доступ к статическим файлам бэкенда
      - media:/media
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend
