volumes:
  pg_data:
  static:
  media:
  redoc:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  backend:
    image: katomy/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static/
      - media:/app/media/
      - redoc:/app/docs/
    command: >
      sh -c "python manage.py makemigrations
      && python manage.py makemigrations recipes
      && python manage.py migrate
      && python manage.py migrate recipes
      && python manage.py collectstatic --noinput
      && python manage.py load_ingridients data/ingredients.json
      && python manage.py load_tags data/tags.json
      && gunicorn --bind 0.0.0.0:8080 backend.wsgi"
    depends_on:
      - db
  frontend:
    image: katomy/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static/
  gateway:
    image: katomy/foodgram_nginx
    env_file: .env
    volumes:
      - static:/static/
      - media:/media/
      - redoc:/redoc/
    depends_on:
      - backend
      - frontend
    ports:
      - 8080:80
