volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static:/static
      - media:/app/media
    command: >
      sh -c "python manage.py makemigrations
      && python manage.py makemigrations recipes
      && python manage.py migrate
      && python manage.py migrate recipes
      && python manage.py collectstatic --noinput
      && python manage.py load_ingridients data/ingredients.json
      && python manage.py load_tags data/tags.json
      && gunicorn --bind 0.0.0.0:8080 backend.wsgi"
    depends_on:
      - db

  frontend:
    env_file: .env
    build: ./frontend/
    command: sh -c "cp -r /app/build/static /static/ && cp /app/build/index.html /static/"
    volumes:
      - static:/static

  nginx:
    build: ./infra/
    env_file: .env
    volumes:
      - static:/static
      - media:/media
    ports:
      - 80:80
    depends_on:
      - backend
