# Generated by Django 3.2.20 on 2023-07-29 22:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(default=0, help_text='Обязательное поле', validators=[django.core.validators.MinValueValidator(1, message='Время готовки должно быть >= 1 минуте')], verbose_name='Время приготовления (в минутах)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(default='морковь', help_text='Обязательное поле', through='recipes.RecipeIngredient', to='recipes.Ingredient', verbose_name='Список ингредиентов'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Количество ингредиентов не должно быть = 0')], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(help_text='Обязательное поле, Цветовой HEX-код, пример #63C144', max_length=7, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(help_text='Обязательное поле, Латинскими буквами', max_length=200, unique=True, validators=[django.core.validators.RegexValidator(message='Неверный формат Никнейма.', regex='^[-a-zA-Z0-9_]+$')], verbose_name='Слаг'),
        ),
        migrations.AlterUniqueTogether(
            name='favoriterecipe',
            unique_together=set(),
        ),
    ]
